@TOKEN_1=IQgkEVsGNEyCV18Bgb4JwDFu37Ur3qVJIieKo8uz
@TOKEN_2=3EAOu9ujOSTJrHMxcSX20DW4guNFdTRNMtG05URw


### Login
curl -X POST http://localhost:8000/api/user/login \
-H 'Content-Type: application/json' \
-H 'Accept: application/json' \
-d '{"email": "admin@mail.com", "password": "power@123"}'

### Get logged user 1
curl -X GET http://localhost:8000/api/me \
-H 'Authorization: Bearer {{ TOKEN_1 }}' \
-H 'Content-Type: application/json' \
-H 'Accept: application/json'

### Get logged user 2
curl -X GET http://localhost:8000/api/me \
-H 'Authorization: Bearer {{ TOKEN_2 }}' \
-H 'Content-Type: application/json' \
-H 'Accept: application/json'


### Create USER
curl -X POST http://localhost:8000/api/user \
-H 'Content-Type: application/json' \
-H 'Accept: application/json' \
-d '{
    "name": "admin2",
    "email": "admin2@mail.com",
    "password": "power@123",
    "password_confirmation": "power@123"
}'

###### MESSAGES #########

### SEND message to user 1
curl -X POST http://localhost:8000/api/messages \
-H 'Authorization: Bearer {{ TOKEN_2 }}' \
-H 'Content-Type: application/json' \
-H 'Accept: application/json' \
-d '{
    "to": 1,
    "message": "Hello world"
}'

### SEND message to user 2
curl -X POST http://localhost:8000/api/messages \
-H 'Authorization: Bearer {{ TOKEN_1 }}' \
-H 'Content-Type: application/json' \
-H 'Accept: application/json' \
-d '{
    "to": 2,
    "message": "Hello world"
}'

### MUST FAILL send to yourself
curl -X POST http://localhost:8000/api/messages \
-H 'Authorization: Bearer {{ TOKEN_1 }}' \
-H 'Content-Type: application/json' \
-H 'Accept: application/json' \
-d '{
    "to": 1,
    "message": "Hello world"
}'

### Get ALL messages to user 1
curl -X GET http://localhost:8000/api/messages \
-H 'Authorization: Bearer {{ TOKEN_1 }}' \
-H 'Content-Type: application/json' \
-H 'Accept: application/json'

### Get ALL messages to user 2
curl -X GET http://localhost:8000/api/messages \
-H 'Authorization: Bearer {{ TOKEN_2 }}' \
-H 'Content-Type: application/json' \
-H 'Accept: application/json'

### Get messages from user 1
curl -X GET http://localhost:8000/api/messages/from/1 \
-H 'Authorization: Bearer {{ TOKEN_2 }}' \
-H 'Content-Type: application/json' \
-H 'Accept: application/json'

### Get messages from user 2
curl -X GET http://localhost:8000/api/messages/from/2 \
-H 'Authorization: Bearer {{ TOKEN_1 }}' \
-H 'Content-Type: application/json' \
-H 'Accept: application/json'
